#! /bin/sh
set -x
switch=br0

if [ -n "$1" ];then
    /usr/bin/sudo /usr/sbin/tunctl -u "$whoami" -t $1
    /usr/bin/sudo /sbin/ip link set $1 up
#    /usr/bin/sudo /sbin/ip link set dev $1 address 52:54:00:12:34:56
    sleep 0.5s
    /usr/bin/sudo /sbin/brctl addif $switch $1
    exit 0
else
    echo "Error: no interface specified"
    exit 1
fi
